import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import Navbar from '../Home/components/Navbar'
import LoadingScreen from '../../components/LoadingScreen'
import { CITY_OPTIONS } from '../../constants/cities'
import { normalizePropertyType, PROPERTY_TYPE_OPTIONS } from '../../constants/propertyTypes'
import { apiRequest } from '../../lib/api'

const backendPropertyTypes = [
  { value: 'all', label: 'All Types' },
  ...PROPERTY_TYPE_OPTIONS.map((item) => ({ value: item, label: item }))
]

const sortOptions = [
  { value: 'newest', label: 'Newest First' },
  { value: 'price_low', label: 'Price: Low to High' },
  { value: 'price_high', label: 'Price: High to Low' }
]

function parseBudgetLabelToNumber(label) {
  if (!label) {
    return ''
  }

  const normalized = String(label).replace(/[^0-9.a-zA-Z ]/g, '').trim().toLowerCase()
  const numberMatch = normalized.match(/[0-9]+(?:\.[0-9]+)?/)
  if (!numberMatch) {
    return ''
  }

  const numeric = Number(numberMatch[0])
  if (Number.isNaN(numeric)) {
    return ''
  }

  if (normalized.includes('cr')) {
    return String(Math.round(numeric * 10000000))
  }

  if (normalized.includes('lac')) {
    return String(Math.round(numeric * 100000))
  }

  return String(Math.round(numeric))
}

function normalizeSearchPropertyType(rawValue) {
  if (!rawValue) {
    return 'all'
  }

  return normalizePropertyType(rawValue) || 'all'
}

function normalizeSearchTextValue(value) {
  return String(value || '').trim().toLowerCase().replace(/\s+/g, ' ')
}

function isAutoGeneratedQuery(queryText, searchType, propertyType, city) {
  const normalizedQuery = normalizeSearchTextValue(queryText)
  if (!normalizedQuery) {
    return false
  }

  const expected = normalizeSearchTextValue(`${searchType} ${propertyType} in ${city}`)
  return normalizedQuery === expected
}

function formatPrice(property) {
  if (!property) return 'Price on request'
  if (typeof property.price === 'number') return `INR ${Number(property.price).toLocaleString('en-IN')}`
  return property.price || 'Price on request'
}

function getPropertyHighlights(property) {
  const details = []
  const residential = property?.specifications?.residential
  const commercial = property?.specifications?.commercial
  const plot = property?.specifications?.plot

  if (residential?.bhk) details.push(`${residential.bhk} BHK`)
  if (residential?.bathrooms) details.push(`${residential.bathrooms} Bath`)
  if (residential?.superBuiltUpArea) details.push(`${residential.superBuiltUpArea} sq ft`)

  if (commercial?.propertyUse) details.push(String(commercial.propertyUse).replace(/^./, (c) => c.toUpperCase()))
  if (commercial?.washrooms) details.push(`${commercial.washrooms} Washroom`)

  if (plot?.plotArea) details.push(`Plot ${plot.plotArea} sq ft`)

  return details.slice(0, 4)
}

function getLocationText(property) {
  const parts = [property?.locality, property?.city, property?.state].filter(Boolean)
  return parts.length > 0 ? parts.join(', ') : 'Location not listed'
}

const SearchResultsPage = () => {
  const navigate = useNavigate()
  const [searchParams, setSearchParams] = useSearchParams()

  const [query, setQuery] = useState(searchParams.get('q') || '')
  const [city, setCity] = useState(searchParams.get('city') || 'All India')
  const [searchType, setSearchType] = useState(searchParams.get('searchType') || 'buy')
  const [propertyType, setPropertyType] = useState(normalizeSearchPropertyType(searchParams.get('propertyType')))
  const [minPrice, setMinPrice] = useState(
    parseBudgetLabelToNumber(searchParams.get('budgetMin')) || searchParams.get('minPrice') || ''
  )
  const [maxPrice, setMaxPrice] = useState(
    parseBudgetLabelToNumber(searchParams.get('budgetMax')) || searchParams.get('maxPrice') || ''
  )
  const [sort, setSort] = useState(searchParams.get('sort') || 'newest')

  const [properties, setProperties] = useState([])
  const [isLoading, setIsLoading] = useState(true)
  const [error, setError] = useState('')

  const listingType = useMemo(() => (searchType === 'rent' ? 'rent' : 'sell'), [searchType])
  const shouldApplyKeywordSearch = useMemo(() => {
    return query.trim() && !isAutoGeneratedQuery(query, searchType, propertyType, city)
  }, [query, searchType, propertyType, city])

  useEffect(() => {
    const next = new URLSearchParams()
    if (query) next.set('q', query)
    if (city) next.set('city', city)
    if (searchType) next.set('searchType', searchType)
    if (propertyType && propertyType !== 'all') next.set('propertyType', propertyType)
    if (minPrice) next.set('minPrice', minPrice)
    if (maxPrice) next.set('maxPrice', maxPrice)
    if (sort) next.set('sort', sort)

    setSearchParams(next, { replace: true })
  }, [query, city, searchType, propertyType, minPrice, maxPrice, sort, setSearchParams])

  useEffect(() => {
    const loadResults = async () => {
      setIsLoading(true)
      setError('')

      try {
        const requestParams = new URLSearchParams({
          status: 'approved',
          limit: '120',
          listingType,
          sortBy: sort === 'newest' ? 'createdAt' : 'price',
          sortOrder: sort === 'price_low' ? 'asc' : 'desc'
        })

        if (shouldApplyKeywordSearch) requestParams.set('search', query.trim())
        if (city && city !== 'All India') requestParams.set('city', city)
        if (propertyType !== 'all') requestParams.set('propertyType', propertyType)
        if (minPrice) requestParams.set('minPrice', minPrice)
        if (maxPrice) requestParams.set('maxPrice', maxPrice)

        const response = await apiRequest(`/properties?${requestParams.toString()}`)
        setProperties(response?.data || [])
      } catch (loadError) {
        setError(loadError.message || 'Failed to load search results')
      } finally {
        setIsLoading(false)
      }
    }

    loadResults()
  }, [query, city, listingType, propertyType, minPrice, maxPrice, sort, shouldApplyKeywordSearch])

  const clearAllFilters = () => {
    setQuery('')
    setCity('All India')
    setSearchType('buy')
    setPropertyType('all')
    setMinPrice('')
    setMaxPrice('')
    setSort('newest')
  }

  return (
    <div className="min-h-screen bg-(--color-surface)">
      <Navbar />

      <section className="mx-auto w-[92%] max-w-7xl py-6">
        <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm lg:p-6">
          <p className="text-xs font-semibold uppercase tracking-[0.2em] text-(--color-secondary-text)">Search Results</p>
          <h1 className="mt-2 text-2xl font-bold text-slate-900 lg:text-3xl">
            Discover properties with advanced filters
          </h1>
          <p className="mt-2 text-sm text-slate-600">
            Refine your search from the left panel and open any property for complete details.
          </p>
        </div>
      </section>

      <section className="mx-auto grid w-[92%] max-w-7xl gap-6 pb-12 lg:grid-cols-[320px_1fr]">
        <aside className="h-fit rounded-3xl border border-slate-200 bg-white p-5 shadow-sm lg:sticky lg:top-24">
          <div className="flex items-center justify-between gap-3">
            <h2 className="text-lg font-semibold text-slate-900">Filters</h2>
            <button
              type="button"
              onClick={clearAllFilters}
              className="rounded-lg border border-slate-300 bg-white px-3 py-1.5 text-xs font-semibold text-slate-700 hover:bg-slate-100"
            >
              Clear All
            </button>
          </div>

          <div className="mt-4 space-y-4">
            <label className="block">
              <span className="text-xs font-semibold uppercase tracking-[0.15em] text-slate-500">Keyword</span>
              <input
                type="text"
                value={query}
                onChange={(event) => setQuery(event.target.value)}
                placeholder="Search by title, city, locality"
                className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-(--color-primary)"
              />
            </label>

            <label className="block">
              <span className="text-xs font-semibold uppercase tracking-[0.15em] text-slate-500">Purpose</span>
              <select
                value={searchType}
                onChange={(event) => setSearchType(event.target.value)}
                className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-(--color-primary)"
              >
                <option value="buy">Buy</option>
                <option value="rent">Rent</option>
              </select>
            </label>

            <label className="block">
              <span className="text-xs font-semibold uppercase tracking-[0.15em] text-slate-500">City</span>
              <select
                value={city}
                onChange={(event) => setCity(event.target.value)}
                className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-(--color-primary)"
              >
                {CITY_OPTIONS.map((item) => (
                  <option key={item} value={item}>{item}</option>
                ))}
              </select>
            </label>

            <label className="block">
              <span className="text-xs font-semibold uppercase tracking-[0.15em] text-slate-500">Property Type</span>
              <select
                value={propertyType}
                onChange={(event) => setPropertyType(event.target.value)}
                className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-(--color-primary)"
              >
                {backendPropertyTypes.map((item) => (
                  <option key={item.value} value={item.value}>{item.label}</option>
                ))}
              </select>
            </label>

            <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-1 xl:grid-cols-2">
              <label className="block">
                <span className="text-xs font-semibold uppercase tracking-[0.15em] text-slate-500">Min Price</span>
                <input
                  type="number"
                  min="0"
                  value={minPrice}
                  onChange={(event) => setMinPrice(event.target.value)}
                  placeholder="e.g. 500000"
                  className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-(--color-primary)"
                />
              </label>
              <label className="block">
                <span className="text-xs font-semibold uppercase tracking-[0.15em] text-slate-500">Max Price</span>
                <input
                  type="number"
                  min="0"
                  value={maxPrice}
                  onChange={(event) => setMaxPrice(event.target.value)}
                  placeholder="e.g. 5000000"
                  className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-(--color-primary)"
                />
              </label>
            </div>

            <label className="block">
              <span className="text-xs font-semibold uppercase tracking-[0.15em] text-slate-500">Sort By</span>
              <select
                value={sort}
                onChange={(event) => setSort(event.target.value)}
                className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-900 outline-none focus:border-(--color-primary)"
              >
                {sortOptions.map((item) => (
                  <option key={item.value} value={item.value}>{item.label}</option>
                ))}
              </select>
            </label>
          </div>
        </aside>

        <div className="space-y-4">
          <div className="flex flex-wrap items-center justify-between gap-3 rounded-3xl border border-slate-200 bg-white px-4 py-3 shadow-sm">
            <p className="text-sm font-semibold text-slate-900">{properties.length} properties found</p>
            <p className="text-xs uppercase tracking-[0.14em] text-slate-500">{searchType === 'rent' ? 'Rent Listings' : 'Buy Listings'}</p>
          </div>

          {isLoading ? (
            <LoadingScreen label="Loading Results" sublabel="Finding properties for your filters" />
          ) : error ? (
            <div className="rounded-3xl border border-rose-200 bg-rose-50 p-5 text-sm text-rose-700 shadow-sm">{error}</div>
          ) : properties.length === 0 ? (
            <div className="rounded-3xl border border-slate-200 bg-white p-6 text-sm text-slate-600 shadow-sm">
              No properties match your current filters. Try relaxing price, city, or type.
            </div>
          ) : (
            <div className="space-y-4">
              {properties.map((property) => {
                const image = Array.isArray(property.images) && property.images.length > 0
                  ? property.images[0]
                  : 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1200&q=80'

                const highlights = getPropertyHighlights(property)
                const amenities = Array.isArray(property.amenities) ? property.amenities.slice(0, 4) : []

                return (
                  <article
                    key={property._id}
                    className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:shadow-lg"
                  >
                    <button
                      type="button"
                      onClick={() => navigate(`/properties/${property._id}`)}
                      className="grid w-full text-left md:grid-cols-[320px_1fr]"
                    >
                      <img src={image} alt={property.title} className="h-56 w-full object-cover md:h-full" />
                      <div className="p-5 lg:p-6">
                        <div className="flex flex-wrap items-start justify-between gap-3">
                          <div>
                            <p className="text-lg font-bold text-(--color-primary)">{formatPrice(property)}</p>
                            <h3 className="mt-1 line-clamp-2 text-xl font-semibold text-slate-900">{property.title}</h3>
                            <p className="mt-2 text-sm text-slate-600">{getLocationText(property)}</p>
                          </div>
                          <span className="rounded-full bg-(--color-secondary-bg) px-3 py-1 text-xs font-semibold uppercase tracking-[0.14em] text-(--color-primary)">
                            {property.listingType === 'rent' ? 'For Rent' : 'For Sale'}
                          </span>
                        </div>

                        <p className="mt-3 line-clamp-2 text-sm text-slate-600">{property.description || 'Description not available.'}</p>

                        <div className="mt-4 flex flex-wrap gap-2">
                          <span className="rounded-lg border border-slate-200 bg-slate-50 px-2.5 py-1 text-xs font-semibold text-slate-700">
                            {property.propertyType}
                          </span>
                          {highlights.map((item) => (
                            <span key={item} className="rounded-lg border border-slate-200 bg-slate-50 px-2.5 py-1 text-xs font-semibold text-slate-700">
                              {item}
                            </span>
                          ))}
                        </div>

                        {amenities.length > 0 ? (
                          <div className="mt-4">
                            <p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-500">Amenities</p>
                            <div className="mt-2 flex flex-wrap gap-2">
                              {amenities.map((amenity) => (
                                <span key={amenity} className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-medium text-slate-700">
                                  {String(amenity).replace(/-/g, ' ')}
                                </span>
                              ))}
                            </div>
                          </div>
                        ) : null}
                      </div>
                    </button>
                  </article>
                )
              })}
            </div>
          )}

          <div>
            <Link to="/" className="inline-flex rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-semibold text-slate-700 transition hover:bg-slate-100">
              Back to Home
            </Link>
          </div>
        </div>
      </section>
    </div>
  )
}

export default SearchResultsPage
